import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import StoreProvider from '@/lib/StoreProvider';
import { ThemeProvider } from "@/components/theme-provider";
// Temporarily comment out I18nProvider to test
// import { I18nProvider } from '@/components/providers/I18nProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "latin-ext", "cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${inter.variable} antialiased`}>
        <StoreProvider>
          {/* Temporarily removed I18nProvider to test */}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}